apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookcatalogue
  namespace: bookcatalogue
  labels:
    app.kubernetes.io/created-by: eks-workshop
    app.kubernetes.io/type: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bookcatalogue
      app.kubernetes.io/instance: bookcatalogue
      app.kubernetes.io/component: service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bookcatalogue
        app.kubernetes.io/instance: bookcatalogue
        app.kubernetes.io/component: service
        app.kubernetes.io/created-by: eks-workshop
    spec:
      containers:
        - name: bookcatalogue
          env:
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: otlp
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://adot-collector.otel:4317
            - name: OTEL_TRACES_SAMPLER
              value: always_on
            - name: OTEL_IMR_EXPORT_INTERVAL
              value: "5000"
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: "5000"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=bookcatalogue,service.version=1.0,deployment.environment=production
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          image: "<ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/bookcatalogue:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 1Gi
